/*
 * Copyright (C) 2020 MyLibreLab
 * Based on MyOpenLab by Carmelo Salafia www.myopenlab.de
 * Copyright (C) 2004  Carmelo Salafia cswi@gmx.de
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.github.mylibrelab.elements.circuit.automation.fuzzycontrol;// *****************************************************************************

/*
 * DialogChart.java
 *
 * Created on 19. Mai 2007, 20:22
 */

import java.awt.*;

import javax.swing.*;

/**
 *
 * @author Carmelo
 */

class MyPanel extends JPanel {
    public JFreeChart chart;

    public MyPanel(JFreeChart chart) {
        this.chart = chart;
    }

    public void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;

        if (chart != null) {
            chart.draw(g2, getBounds());
        }

    }
}


public class DialogChart extends javax.swing.JDialog {

    public Variable var;
    public MyNode node;
    private MyPanel panel;


    /** Creates new form DialogChart */
    public DialogChart(java.awt.Frame parent, boolean modal, String title) {
        super(parent, modal);
        initComponents();
        setLocationByPlatform(true);
        setTitle(title);
    }

    public void close() {
        var = null;
        node = null;
        dispose();
    }


    public void init(JFreeChart chart, Variable var, MyNode node) {
        this.node = node;
        this.var = var;
        panel = new MyPanel(chart);
        getContentPane().add(panel, BorderLayout.CENTER);
    }

    public void updateChart(JFreeChart chart, Variable var, MyNode node) {
        this.node = node;
        this.var = var;
        panel.chart = chart;

        panel.updateUI();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        // java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        // setBounds((screenSize.width-408)/2, (screenSize.height-327)/2, 408, 327);
        setSize(400, 320);

    }// </editor-fold>


}
