name: Autostyle

on: [push, pull_request]

jobs:
  autostlye:
    name: "Autostyle"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check
        run: ./gradlew autostyleCheck
