name: Autostyle

on: [push, pull_request]

jobs:
  autostlye:
    name: "Autostyle"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check
        run: ./gradlew autostyleCheck
