name: Deployment

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            displayName: linux
            archivePortable: ls -la build && ls -la build/jpackage && mkdir build/distribution && mv build/image.zip build/distribution/MyLibreLab-linux.zip
          - os: windows-latest
            displayName: windows
            archivePortable: mkdir build/distribution && mv build/image.zip build/distribution/MyLibreLab-windows.zip && 7z a -r build/distribution/MyLibreLab-portable_windows.zip build/jpackage/MyLibreLab
          - os: macOS-latest
            displayName: macOS
            archivePortable: ls -la build && ls -la build/jpackage && mkdir build/distribution && mv build/image.zip build/distribution/MyLibreLab-macos.zip

    runs-on: ${{ matrix.os }}
    name: Create installer and portable version for ${{ matrix.displayName }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Restore gradle cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - name: Cache gradle wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Build
        run: ./gradlew build -PskipAutostyle -PskipSonarlint
      - name: Build runtime image
        run: ./gradlew :mylibrelab-application:runtimeZip -PskipAutostyle -PskipSonarlint
      - name: Build installer
        run: ./gradlew :mylibrelab-application:jpackage -PskipAutostyle -PskipSonarlint
        shell: bash