name: Sonarlint

on: [push, pull_request]

jobs:
  sonarlint:
    name: "Sonarlint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Check
        run: ./gradlew sonarlintMain